catalogs:
  binary:
    eslint: ^9.39.2
  dev:
    eslint-typegen: ^2.3.0
  helper:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^0.11.0
    globals: ^17.1.0
    local-pkg: ^1.1.2
  infra:
    jiti: ^2.6.1
    simple-git-hooks: ^2.13.1
    tsdown: ^0.20.1
    typescript: ^5.9.3
  optional:
    '@typescript-eslint/eslint-plugin': ^8.53.1
    '@typescript-eslint/parser': ^8.53.1
    eslint-config-prettier: ^10.1.8
    eslint-plugin-format: ^1.3.1
    eslint-plugin-prettier: ^5.5.5
    eslint-plugin-vue: ^10.7.0
    prettier: ^3.8.1
    vue-eslint-parser: ^10.2.0
  required:
    '@eslint/js': ^9.39.2
    eslint-plugin-import: ^2.32.0
    eslint-plugin-perfectionist: ^5.4.0
    eslint-plugin-unicorn: ^62.0.0
  typing:
    '@types/node': ^22.19.7

cleanupUnusedCatalogs: true

overrides:
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  diff@>=6.0.0 <8.0.3: '>=8.0.3'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
