catalog:
  '@eslint-react/eslint-plugin': 5.7.3
  '@typescript-eslint/eslint-plugin': ^8.59.2
  eslint: ^10.3.0
  eslint-plugin-import-x: ^4.16.2
  eslint-plugin-perfectionist: ^5.9.0
  eslint-plugin-prettier: ^5.5.5
  eslint-plugin-simple-import-sort: ^13.0.0
  eslint-plugin-sonarjs: ^4.0.3
  eslint-plugin-unicorn: ^64.0.0
  eslint-plugin-vue: ^10.9.1

catalogMode: prefer

catalogs:
  helper:
    globals: ^17.6.0
    local-pkg: ^1.1.2
  infra:
    eslint-typegen: ^2.3.1
    jiti: ^2.7.0
    nano-staged: ^1.0.2
    simple-git-hooks: ^2.13.1
    tsdown: ^0.21.10
    typescript: ^6.0.3
  lint:
    '@eslint/js': ^10.0.1
    '@typescript-eslint/parser': ^8.59.2
    eslint-config-prettier: ^10.1.8
    prettier: ^3.8.3
    vue-eslint-parser: ^10.4.0
  typing:
    '@types/node': ^25.6.0

cleanupUnusedCatalogs: true
