catalogs:
  binary:
    eslint: ^9.39.2
  dev:
    '@eslint/config-inspector': ^1.3.0
    eslint-typegen: ^2.3.0
  helper:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^0.11.0
    globals: ^17.0.0
    local-pkg: ^1.1.2
  infra:
    bumpp: ^10.3.1
    cspell: ^9.2.2
    jiti: ^2.6.1
    simple-git-hooks: ^2.13.1
    tsdown: ^0.15.12
    typescript: ^5.9.3
  optional:
    '@eslint-react/eslint-plugin': ^2.5.1
    '@typescript-eslint/eslint-plugin': ^8.52.0
    '@typescript-eslint/parser': ^8.52.0
    eslint-config-prettier: ^10.1.8
    eslint-plugin-prettier: ^5.5.4
    eslint-plugin-format: ^1.2.0
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.26
    eslint-plugin-vue: ^10.6.2
    prettier: ^3.7.4
    vue-eslint-parser: ^10.2.0
  required:
    '@eslint/js': ^9.39.2
    eslint-plugin-import: ^2.32.0
    eslint-plugin-simple-import-sort: ^12.1.1
    eslint-plugin-unicorn: ^62.0.0
  typing:
    '@types/node': ^22.18.9

cleanupUnusedCatalogs: true
