name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm ci

      - name: Typegen
        run: pnpm typegen

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck
