name: Publish Package

on:
  push:
    tags:
      - v*

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v6

      - name: Install node
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Install pnpm
      - uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
      - run: pnpm ci

      - name: Typegen
      - run: pnpm typegen

      - name: Typecheck
      - run: pnpm typecheck

      - name: Build
      - run: pnpm build

      - name: Publish
      - run: pnpm publish
